/* ==========================================================
   WATER MANAGEMENT SYSTEM - BACKEND SERVER (HTTP-ONLY + AUTH)
   ========================================================== */

const express = require("express");
const cors = require("cors");
const crypto = require("crypto");
const http = require("http");
const WebSocket = require("ws");

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static("public"));

const PORT = process.env.PORT || 3000;

const server = http.createServer(app);
const wss = new WebSocket.Server({ server, path: "/device-ws" });

// key: apartment/floor/flat -> live WebSocket connection for that ESP32
const deviceSockets = {};

wss.on("connection", (ws) => {
  let deviceKey = null;

  ws.on("message", (raw) => {
    let msg;
    try { msg = JSON.parse(raw); } catch (e) { return; }

    if (msg.type === "register") {
      deviceKey = keyFor(msg.apartment, msg.floor, msg.flat);
      deviceSockets[deviceKey] = ws;
      console.log(`Device connected via WebSocket: ${deviceKey}`);
    }
  });

  ws.on("close", () => {
    if (deviceKey && deviceSockets[deviceKey] === ws) {
      delete deviceSockets[deviceKey];
      console.log(`Device disconnected: ${deviceKey}`);
    }
  });
});

// ---------------- IN-MEMORY DATA STORE ----------------
// NOTE: This resets whenever the server restarts (e.g. free-tier sleep).
// For production, replace with a real database (e.g. Supabase/Postgres).
const flatsData = {};
const history = {};
const pendingCommands = {};
const users = {};          // key: phone -> user record
const sessions = {};       // key: token -> phone
const limits = {};         // key: apartment/floor/flat -> daily liter limit
const invites = {};        // key: invite token -> { apartment, floor, flat, used, createdAt }
const alertsSent = {};     // key: apartment/floor/flat -> { level80: bool, level100: bool }
const notifications = {};  // key: apartment/floor/flat -> array of { level, message, timestamp }
const adminNotifications = []; // flat-independent feed for admins

const MAX_HISTORY = 200;

function keyFor(apartment, floor, flat) {
  return `${apartment}/${floor}/${flat}`;
}

function hashPassword(password, salt) {
  return crypto.scryptSync(password, salt, 64).toString("hex");
}

function makeToken() {
  return crypto.randomBytes(24).toString("hex");
}

// ---------------- AUTH MIDDLEWARE ----------------
function requireAuth(req, res, next) {
  const authHeader = req.headers.authorization || "";
  const token = authHeader.replace("Bearer ", "");
  const phone = sessions[token];
  if (!phone || !users[phone]) {
    return res.status(401).json({ error: "Not authenticated" });
  }
  req.user = users[phone];
  next();
}

function requireAdmin(req, res, next) {
  if (req.user.role !== "admin") {
    return res.status(403).json({ error: "Admin only" });
  }
  next();
}

// ================= AUTH ROUTES =================

// Signup: only "admin" role can self-signup here.
// Flat owners must sign up via a specific invite link generated by an admin (see /api/invites).
app.post("/api/auth/signup", (req, res) => {
  const { role, name, phone, password } = req.body;

  if (role !== "admin") {
    return res.status(403).json({ error: "Flat owners must sign up using an invite link from their apartment admin." });
  }
  if (!name || !phone || !password) {
    return res.status(400).json({ error: "Missing required fields" });
  }
  if (users[phone]) {
    return res.status(409).json({ error: "An account with this phone number already exists" });
  }

  const salt = crypto.randomBytes(16).toString("hex");
  const passwordHash = hashPassword(password, salt);

  users[phone] = {
    role: "admin", name, phone, salt, passwordHash,
    apartment: null, floor: null, flat: null,
    createdAt: new Date().toISOString(),
  };

  const token = makeToken();
  sessions[token] = phone;

  const { salt: _s, passwordHash: _p, ...safeUser } = users[phone];
  res.json({ success: true, token, user: safeUser });
});

// ---------------- INVITE-BASED FLAT OWNER SIGNUP ----------------

// Admin creates an invite link for a specific flat
app.post("/api/invites", requireAuth, requireAdmin, (req, res) => {
  const { apartment, floor, flat } = req.body;
  if (!apartment || !floor || !flat) {
    return res.status(400).json({ error: "apartment, floor, flat are required" });
  }

  const key = keyFor(apartment, floor, flat);
  const alreadyHasOwner = Object.values(users).some(
    (u) => u.role === "flat_owner" && keyFor(u.apartment, u.floor, u.flat) === key
  );
  if (alreadyHasOwner) {
    return res.status(409).json({ error: "This flat already has an owner account. Delete it first to re-invite." });
  }

  const token = crypto.randomBytes(12).toString("hex");
  invites[token] = { apartment, floor, flat, used: false, createdAt: new Date().toISOString() };

  res.json({ success: true, token, apartment, floor, flat });
});

// Look up invite details (used by the signup page to show the predefined apartment/flat)
app.get("/api/invites/:token", (req, res) => {
  const invite = invites[req.params.token];
  if (!invite) return res.status(404).json({ error: "Invalid or expired invite link" });
  if (invite.used) return res.status(410).json({ error: "This invite link has already been used" });
  res.json({ apartment: invite.apartment, floor: invite.floor, flat: invite.flat });
});

// Flat owner completes signup through their invite link
app.post("/api/auth/signup-with-invite", (req, res) => {
  const { token, name, phone, password } = req.body;
  const invite = invites[token];

  if (!invite) return res.status(404).json({ error: "Invalid or expired invite link" });
  if (invite.used) return res.status(410).json({ error: "This invite link has already been used" });
  if (!name || !phone || !password) return res.status(400).json({ error: "Missing required fields" });
  if (users[phone]) return res.status(409).json({ error: "An account with this phone number already exists" });

  const salt = crypto.randomBytes(16).toString("hex");
  const passwordHash = hashPassword(password, salt);

  users[phone] = {
    role: "flat_owner", name, phone, salt, passwordHash,
    apartment: invite.apartment, floor: invite.floor, flat: invite.flat,
    createdAt: new Date().toISOString(),
  };
  invite.used = true;

  const authToken = makeToken();
  sessions[authToken] = phone;

  const { salt: _s, passwordHash: _p, ...safeUser } = users[phone];
  res.json({ success: true, token: authToken, user: safeUser });
});

// Admin deletes a flat owner's account (frees up the flat for a new invite)
app.delete("/api/users/:apartment/:floor/:flat", requireAuth, requireAdmin, (req, res) => {
  const { apartment, floor, flat } = req.params;
  const key = keyFor(apartment, floor, flat);

  const phoneToDelete = Object.keys(users).find(
    (p) => users[p].role === "flat_owner" && keyFor(users[p].apartment, users[p].floor, users[p].flat) === key
  );
  if (!phoneToDelete) return res.status(404).json({ error: "No account found for this flat" });

  delete users[phoneToDelete];
  Object.keys(sessions).forEach((t) => { if (sessions[t] === phoneToDelete) delete sessions[t]; });

  res.json({ success: true });
});

// Login
app.post("/api/auth/login", (req, res) => {
  const { phone, password } = req.body;
  const user = users[phone];
  if (!user) return res.status(401).json({ error: "Invalid phone number or password" });

  const attemptHash = hashPassword(password, user.salt);
  if (attemptHash !== user.passwordHash) {
    return res.status(401).json({ error: "Invalid phone number or password" });
  }

  const token = makeToken();
  sessions[token] = phone;

  const { salt: _s, passwordHash: _p, ...safeUser } = user;
  res.json({ success: true, token, user: safeUser });
});

// Get current logged-in user
app.get("/api/auth/me", requireAuth, (req, res) => {
  const { salt: _s, passwordHash: _p, ...safeUser } = req.user;
  res.json({ user: safeUser });
});

// ---------------- HEALTH CHECK ----------------
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// ================= ESP32 -> BACKEND (no auth, device-to-server) =================

app.post("/api/device/data/:apartment/:floor/:flat", (req, res) => {
  const { apartment, floor, flat } = req.params;
  const key = keyFor(apartment, floor, flat);
  const { flow_lpm, total_liters, valve_status } = req.body;

  const record = {
    apartment, floor, flat,
    flow_lpm, total_liters, valve_status,
    received_at: new Date().toISOString(),
  };

  flatsData[key] = record;
  if (!history[key]) history[key] = [];
  history[key].push(record);
  if (history[key].length > MAX_HISTORY) history[key].shift();

  checkLimitAlerts(key, record);

  console.log(`Data from ${key}:`, record);
  res.json({ success: true });
});

function checkLimitAlerts(key, record) {
  const limit = limits[key];
  if (!limit || !record.total_liters) return;

  if (!alertsSent[key]) alertsSent[key] = { level80: false, level100: false };
  const pct = record.total_liters / limit;
  const [apartment, floor, flat] = key.split("/");

  if (pct >= 1 && !alertsSent[key].level100) {
    pushNotification(key, "danger", `Flat ${flat} has reached 100% of its daily water limit (${record.total_liters.toFixed(1)}L of ${limit}L).`);
    alertsSent[key].level100 = true;
  } else if (pct >= 0.8 && !alertsSent[key].level80) {
    pushNotification(key, "warning", `Flat ${flat} is at ${(pct * 100).toFixed(0)}% of its daily water limit (${record.total_liters.toFixed(1)}L of ${limit}L).`);
    alertsSent[key].level80 = true;
  }
}

function pushNotification(key, level, message) {
  if (!notifications[key]) notifications[key] = [];
  const note = { level, message, timestamp: new Date().toISOString() };
  notifications[key].unshift(note);
  adminNotifications.unshift({ key, ...note });
  console.log(`ALERT [${key}]: ${message}`);
}

app.get("/api/device/command/:apartment/:floor/:flat", (req, res) => {
  const { apartment, floor, flat } = req.params;
  const key = keyFor(apartment, floor, flat);
  const command = pendingCommands[key] || null;
  pendingCommands[key] = null;
  res.json({ command });
});

// ================= APP/DASHBOARD -> BACKEND (auth required) =================

// Admin: get all flats' latest data (includes limit + signed-up flat owner name)
app.get("/api/flats", requireAuth, requireAdmin, (req, res) => {
  const keys = new Set([
    ...Object.keys(flatsData),
    ...Object.values(users).filter(u => u.role === "flat_owner").map(u => keyFor(u.apartment, u.floor, u.flat)),
  ]);

  const result = [...keys].map((key) => {
    const owner = Object.values(users).find(
      (u) => u.role === "flat_owner" && keyFor(u.apartment, u.floor, u.flat) === key
    );
    const [apartment, floor, flat] = key.split("/");
    return {
      apartment, floor, flat,
      owner_name: owner ? owner.name : null,
      owner_phone: owner ? owner.phone : null,
      ...flatsData[key],
      limit: limits[key] || null,
    };
  });

  res.json(result);
});

// Get one flat's data — flat owner can only view their own flat; admin can view any
app.get("/api/flats/:apartment/:floor/:flat", requireAuth, (req, res) => {
  const { apartment, floor, flat } = req.params;
  const key = keyFor(apartment, floor, flat);

  if (req.user.role !== "admin") {
    const ownKey = keyFor(req.user.apartment, req.user.floor, req.user.flat);
    if (ownKey !== key) {
      return res.status(403).json({ error: "You can only view your own flat" });
    }
  }

  res.json({
    latest: flatsData[key] || null,
    history: history[key] || [],
    limit: limits[key] || null,
  });
});

// Set valve command — flat owner can control only their own flat; admin can control any
app.post("/api/valve/:apartment/:floor/:flat", requireAuth, (req, res) => {
  const { apartment, floor, flat } = req.params;
  const { action } = req.body;
  const key = keyFor(apartment, floor, flat);

  if (req.user.role !== "admin") {
    const ownKey = keyFor(req.user.apartment, req.user.floor, req.user.flat);
    if (ownKey !== key) {
      return res.status(403).json({ error: "You can only control your own flat's valve" });
    }
  }

  if (!["OPEN", "CLOSE"].includes(action)) {
    return res.status(400).json({ error: "action must be OPEN or CLOSE" });
  }

  // Instant delivery if the ESP32 has an active WebSocket connection
  const liveSocket = deviceSockets[key];
  if (liveSocket && liveSocket.readyState === WebSocket.OPEN) {
    liveSocket.send(JSON.stringify({ command: action }));
    console.log(`Command sent INSTANTLY via WebSocket to ${key}: ${action}`);
  } else {
    console.log(`Device ${key} not connected via WebSocket — queuing for next poll`);
  }

  // Always also queue it, as a fallback in case the push is missed
  pendingCommands[key] = action;
  console.log(`Command queued for ${key}: ${action} (by ${req.user.role} ${req.user.name})`);
  res.json({ success: true, apartment, floor, flat, action, delivered_instantly: !!(liveSocket && liveSocket.readyState === WebSocket.OPEN) });
});

// Admin: set a daily liter limit for a flat
app.post("/api/limits/:apartment/:floor/:flat", requireAuth, requireAdmin, (req, res) => {
  const { apartment, floor, flat } = req.params;
  const { daily_limit_liters } = req.body;
  const key = keyFor(apartment, floor, flat);
  limits[key] = daily_limit_liters;
  alertsSent[key] = { level80: false, level100: false }; // reset alerts when limit changes
  res.json({ success: true, key, daily_limit_liters });
});

// Notifications: flat owner sees their own flat's alerts; admin sees all flats' alerts
app.get("/api/notifications", requireAuth, (req, res) => {
  if (req.user.role === "admin") {
    return res.json(adminNotifications.slice(0, 50));
  }
  const key = keyFor(req.user.apartment, req.user.floor, req.user.flat);
  res.json(notifications[key] || []);
});

// ---------------- START SERVER ----------------
server.listen(PORT, () => {
  console.log(`Backend (HTTP + WebSocket + Auth) running on port ${PORT}`);
});
